# Generated by Django 5.0.3 on 2024-07-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseArtisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=255)),
                ('structure_juridique', models.CharField(blank=True, max_length=255)),
                ('adresse_mail_entreprise', models.EmailField(max_length=254)),
                ('secteur_activite', models.CharField(max_length=255)),
                ('numero_telephone_entreprise', models.CharField(max_length=20)),
                ('adresse_entreprise', models.CharField(max_length=255)),
                ('nom_prenom_artisan', models.CharField(max_length=255)),
                ('adresse_mail_artisan', models.EmailField(max_length=254)),
                ('numero_telephone_artisan', models.CharField(max_length=20)),
                ('adresse_artisan', models.CharField(max_length=255)),
                ('annees_experience', models.CharField(max_length=255)),
                ('fonction_dans_entreprise', models.CharField(max_length=255)),
                ('horaires_travail', models.CharField(max_length=255)),
                ('photo_artisan', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='demandeservice3',
            name='budjet',
        ),
        migrations.RemoveField(
            model_name='demandeservice3',
            name='contact_preference',
        ),
        migrations.RemoveField(
            model_name='demandeservice3',
            name='disponibilite',
        ),
        migrations.RemoveField(
            model_name='demandeservice3',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='demandeservice3',
            name='ville',
        ),
    ]
