# Generated by Django 5.0.7 on 2024-08-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0005_contactuser_delete_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('mecanique', 'Mécanique'), ('electricite', 'Électricité'), ('plomberie', 'Plomberie'), ('peinture', 'Peinture'), ('carrelage', 'Carrelage'), ('maintenance', 'Maintenance'), ('divers', 'Divers')], max_length=50)),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceFirst',
        ),
    ]
