# Generated by Django 5.0.7 on 2024-08-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0006_servicetype_delete_servicefirst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('nom_complet', models.CharField(max_length=255)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('secteur_activite', models.CharField(max_length=255)),
                ('annees_experience', models.PositiveIntegerField()),
                ('fonction', models.CharField(max_length=255)),
                ('horaires_travail', models.CharField(blank=True, max_length=255)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='NUMARTISAPP.entrepriseartisan')),
            ],
        ),
    ]
