# Generated by Django 5.0.7 on 2024-08-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0007_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='typeservice',
            field=models.CharField(choices=[('nettoyage', 'Nettoyage à domicile'), ('mecanique', 'Mécanique'), ('menuiserie', 'Menuiserie')], max_length=50),
        ),
    ]
