# Generated by Django 5.0.7 on 2024-08-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0010_artisan_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='Profile',
        ),
    ]
