# Generated by Django 5.0.7 on 2024-08-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0011_rename_profil_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Pack 1: Abonnement Free'), ('premium', 'Pack 2: Abonnement Premium')], max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('nom_complet', models.CharField(max_length=255)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('secteur_activite', models.CharField(max_length=255)),
                ('annees_experience', models.PositiveIntegerField()),
                ('fonction', models.CharField(max_length=255)),
                ('horaires_travail', models.CharField(blank=True, max_length=255)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='NUMARTISAPP.entrepriseartisan')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
