# Generated by Django 5.0.7 on 2024-08-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0012_subscriptionpack_profil_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpack',
            name='name',
            field=models.CharField(choices=[('Forfait de Base', 'Pack 1: Abonnement de Base'), ('Forfait Avancé', 'Pack 2: Abonnement Avancé'), ('Forfait Premium', 'Pack 2: Abonnement Premium')], max_length=100),
        ),
    ]
